/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseStepContentPanel.java
 *
 * Created on May 14, 2010, 5:31:50 PM
 */

package MainProgram.Walkthrough.UI.StepContentPanels;

import Global.BrowserLauncher;

/**
 *
 * @author Stephen
 */
public class Segment5Step3ContentPanel_All extends BaseStepContentPanel
{
    public Segment5Step3ContentPanel_All()
    {
        initComponents();
    }
    
    @Override
    public boolean WaitForPanelClose()
    {
        return true;
    }
    
    @Override
    public void InitControls()
    {
    }

    @Override
    public void ProcessControlContentToMapData()
    {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        v_tripleaMapCreatorForums = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        v_tripleaDevelopmentForums = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment5Step3ContentPanel_All.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        v_tripleaMapCreatorForums.setText(resourceMap.getString("v_tripleaMapCreatorForums.text")); // NOI18N
        v_tripleaMapCreatorForums.setName("v_tripleaMapCreatorForums"); // NOI18N
        v_tripleaMapCreatorForums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_tripleaMapCreatorForumsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 25;
        jPanel2.add(v_tripleaMapCreatorForums, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(jPanel2, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        v_tripleaDevelopmentForums.setText(resourceMap.getString("v_tripleaDevelopmentForums.text")); // NOI18N
        v_tripleaDevelopmentForums.setName("v_tripleaDevelopmentForums"); // NOI18N
        v_tripleaDevelopmentForums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_tripleaDevelopmentForumsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 25;
        jPanel1.add(v_tripleaDevelopmentForums, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_tripleaDevelopmentForumsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_tripleaDevelopmentForumsActionPerformed
    {//GEN-HEADEREND:event_v_tripleaDevelopmentForumsActionPerformed
        BrowserLauncher.openURL("http://triplea.sourceforge.net/mywiki/Forum");
}//GEN-LAST:event_v_tripleaDevelopmentForumsActionPerformed

    private void v_tripleaMapCreatorForumsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_tripleaMapCreatorForumsActionPerformed
    {//GEN-HEADEREND:event_v_tripleaMapCreatorForumsActionPerformed
        BrowserLauncher.openURL("http://sites.google.com/site/tripleamapcreator/forums");
    }//GEN-LAST:event_v_tripleaMapCreatorForumsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton v_tripleaDevelopmentForums;
    private javax.swing.JButton v_tripleaMapCreatorForums;
    // End of variables declaration//GEN-END:variables
}
