/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Segment1Step1ContentPanel.java
 *
 * Created on May 14, 2010, 5:34:30 PM
 */

package MainProgram.Walkthrough.UI.StepContentPanels;

import MainProgram.Map.ScrollWrapOption;
import Resources.ResourceAddingWindow;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Stephen
 */
public class Segment1Step1ContentPanel_All extends BaseStepContentPanel
{
    /** Creates new form Segment1Step1ContentPanel */
    public Segment1Step1ContentPanel_All()
    {
        initComponents();
    }
    @Override
    public boolean WaitForPanelClose()
    {
        return true;
    }

    @Override
    public void InitControls()
    {
        v_mapNameTxt.setText(m_walkthroughWindow.GetProject().GetMapData().GetMapName());
        v_mapVersionTxt.setText(m_walkthroughWindow.GetProject().GetMapData().GetMapVersion());
        if(m_walkthroughWindow.GetProject().GetMapData().GetScrollWrapOption() == ScrollWrapOption.None)
            v_scrollWrapComboBox.setSelectedIndex(0);
        else if(m_walkthroughWindow.GetProject().GetMapData().GetScrollWrapOption() == ScrollWrapOption.Horizontal)
            v_scrollWrapComboBox.setSelectedIndex(1);
        else if(m_walkthroughWindow.GetProject().GetMapData().GetScrollWrapOption() == ScrollWrapOption.Vertical)
            v_scrollWrapComboBox.setSelectedIndex(2);
        else
            v_scrollWrapComboBox.setSelectedIndex(3);
        v_unitSizeSlider.setValue(GetSliderValueForUnitScale(m_walkthroughWindow.GetProject().GetMapData().GetUnitScale()));
        UpdateUnitPreview();
    }
    @Override
    public void ProcessControlContentToMapData()
    {
        m_walkthroughWindow.GetProject().GetMapData().SetMapName(v_mapNameTxt.getText());
        m_walkthroughWindow.GetProject().GetMapData().SetMapVersion(v_mapVersionTxt.getText());
        if(v_scrollWrapComboBox.getSelectedIndex() == 0)
            m_walkthroughWindow.GetProject().GetMapData().SetScrollWrapOption(ScrollWrapOption.None);
        else if(v_scrollWrapComboBox.getSelectedIndex() == 1)
            m_walkthroughWindow.GetProject().GetMapData().SetScrollWrapOption(ScrollWrapOption.Horizontal);
        else if(v_scrollWrapComboBox.getSelectedIndex() == 2)
            m_walkthroughWindow.GetProject().GetMapData().SetScrollWrapOption(ScrollWrapOption.Vertical);
        else
            m_walkthroughWindow.GetProject().GetMapData().SetScrollWrapOption(ScrollWrapOption.Both);
        m_walkthroughWindow.GetProject().GetMapData().SetUnitScale(GetUnitScaleForSliderValue(v_unitSizeSlider.getValue()));
    }
    private int m_lastDrawnSliderVal = -1;
    private void UpdateUnitPreview()
    {
        if(m_lastDrawnSliderVal == v_unitSizeSlider.getValue())
            return; //Don't update unless we have to
        m_lastDrawnSliderVal = v_unitSizeSlider.getValue();
        
        double scale = GetUnitScaleForSliderValue(v_unitSizeSlider.getValue());
        String scaleTS = Double.toString(scale);
        
        Dimension size = new Dimension((int)(48 * scale),(int)(48 * scale));
        v_unitSizeExample.setToolTipText(scaleTS.substring(0, Math.min(scaleTS.length(), 4)));        
        Image resized = ResourceAddingWindow.GetImage("marine.png").getScaledInstance(size.width, size.height, BufferedImage.SCALE_SMOOTH);
        v_unitSizeExample.setIcon(new ImageIcon(resized));        
    }
    private double GetUnitScaleForSliderValue(int sliderValue)
    {
        switch (sliderValue)
        {
            case 1:
                return .5;
            case 2:
                return .5625;
            case 3:
                return .6666;
            case 4:
                return .75;
            case 5:
                return .8333;
            case 6:
                return .875;
            case 7:
                return 1;
            case 8:
                return 1.25;
        }
        return 0;
    }
    
    private int GetSliderValueForUnitScale(double scale)
    {
        if (scale == .5)
            return 1;
        else if (scale == .5625)
            return 2;
        else if (scale == .6666)
            return 3;
        else if (scale == .75)
            return 4;
        else if (scale == .8333)
            return 5;
        else if (scale == .875)
            return 6;
        else if (scale == 1)
            return 7;
        else if (scale == 1.25)
            return 8;
        else
            return 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        v_mapNameTxt = new javax.swing.JTextField();
        v_mapVersionTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        v_unitSizeSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        v_scrollWrapComboBox = new javax.swing.JComboBox();
        v_unitSizeExample = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(331, 181));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(331, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment1Step1ContentPanel_All.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        v_mapNameTxt.setText(resourceMap.getString("v_mapNameTxt.text")); // NOI18N
        v_mapNameTxt.setToolTipText(resourceMap.getString("v_mapNameTxt.toolTipText")); // NOI18N
        v_mapNameTxt.setName("v_mapNameTxt"); // NOI18N
        jPanel1.add(v_mapNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, -1));

        v_mapVersionTxt.setText(resourceMap.getString("v_mapVersionTxt.text")); // NOI18N
        v_mapVersionTxt.setToolTipText(resourceMap.getString("v_mapVersionTxt.toolTipText")); // NOI18N
        v_mapVersionTxt.setName("v_mapVersionTxt"); // NOI18N
        jPanel1.add(v_mapVersionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, -1));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        v_unitSizeSlider.setMajorTickSpacing(4);
        v_unitSizeSlider.setMaximum(8);
        v_unitSizeSlider.setMinimum(1);
        v_unitSizeSlider.setMinorTickSpacing(1);
        v_unitSizeSlider.setPaintTicks(true);
        v_unitSizeSlider.setSnapToTicks(true);
        v_unitSizeSlider.setToolTipText(resourceMap.getString("v_unitSizeSlider.toolTipText")); // NOI18N
        v_unitSizeSlider.setValue(7);
        v_unitSizeSlider.setName("v_unitSizeSlider"); // NOI18N
        v_unitSizeSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SliderMouseReleased(evt);
            }
        });
        v_unitSizeSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SliderMouseDragged(evt);
            }
        });
        v_unitSizeSlider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SliderKeyReleased(evt);
            }
        });
        jPanel1.add(v_unitSizeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, -1));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        v_scrollWrapComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Scroll Wrap", "Horizontal Scroll Wrap", "Vertical Scroll Wrap", "Hor. and Vert. Scroll Wrap" }));
        v_scrollWrapComboBox.setToolTipText(resourceMap.getString("v_scrollWrapComboBox.toolTipText")); // NOI18N
        v_scrollWrapComboBox.setName("v_scrollWrapComboBox"); // NOI18N
        jPanel1.add(v_scrollWrapComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        v_unitSizeExample.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v_unitSizeExample.setIcon(resourceMap.getIcon("v_unitSizeExample.icon")); // NOI18N
        v_unitSizeExample.setText(resourceMap.getString("v_unitSizeExample.text")); // NOI18N
        v_unitSizeExample.setIconTextGap(0);
        v_unitSizeExample.setName("v_unitSizeExample"); // NOI18N
        jPanel1.add(v_unitSizeExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 68, 68));

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void SliderMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SliderMouseReleased
    {//GEN-HEADEREND:event_SliderMouseReleased
        UpdateUnitPreview();
    }//GEN-LAST:event_SliderMouseReleased

    private void SliderKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SliderKeyReleased
    {//GEN-HEADEREND:event_SliderKeyReleased
        UpdateUnitPreview();
    }//GEN-LAST:event_SliderKeyReleased

    private void SliderMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SliderMouseDragged
    {//GEN-HEADEREND:event_SliderMouseDragged
        if(v_unitSizeSlider.getValueIsAdjusting())
            UpdateUnitPreview();
    }//GEN-LAST:event_SliderMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField v_mapNameTxt;
    private javax.swing.JTextField v_mapVersionTxt;
    private javax.swing.JComboBox v_scrollWrapComboBox;
    private javax.swing.JLabel v_unitSizeExample;
    private javax.swing.JSlider v_unitSizeSlider;
    // End of variables declaration//GEN-END:variables
}
