/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * BaseStepContentPanel.java
 *
 * Created on May 14, 2010, 5:31:50 PM
 */

package MainProgram.Walkthrough.UI.StepContentPanels;

import MainProgram.ProgramLaunchers.ProgramLauncher;
import java.awt.BorderLayout;
import java.awt.Dialog.ModalityType;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Stephen
 */
public class Segment4Step2ContentPanel_All extends BaseStepContentPanel
{
    public Segment4Step2ContentPanel_All()
    {
        initComponents();
    }
    
    private String m_notes = "";
    
    @Override
    public boolean WaitForPanelClose()
    {        
        return true;
    }
    
    @Override
    public void InitControls()
    {
        m_notes = GetMapData().GetMapNotes();
        v_mapNotes.setText(m_notes);
    }

    @Override
    public void ProcessControlContentToMapData()
    {
        m_notes = v_mapNotes.getText();
        GetMapData().SetMapNotes(m_notes);
    }
    
    private long m_lastClickTime = 0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        v_mapNotesScrollPane = new javax.swing.JScrollPane();
        v_mapNotes = new javax.swing.JTextArea();
        v_alignmentHelper1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        v_insertHelperListScrollPane = new javax.swing.JScrollPane();
        v_insertHelperList = new javax.swing.JList();
        v_alignmentHelper2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        v_preview = new javax.swing.JButton();

        v_mapNotesScrollPane.setName("v_mapNotesScrollPane"); // NOI18N

        v_mapNotes.setColumns(20);
        v_mapNotes.setRows(5);
        v_mapNotes.setName("v_mapNotes"); // NOI18N
        v_mapNotesScrollPane.setViewportView(v_mapNotes);

        v_alignmentHelper1.setName("v_alignmentHelper1"); // NOI18N
        v_alignmentHelper1.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment4Step2ContentPanel_All.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        v_alignmentHelper1.add(jLabel1, gridBagConstraints);

        v_insertHelperListScrollPane.setName("v_insertHelperListScrollPane"); // NOI18N

        v_insertHelperList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Big Style (<big>Big Text</big>)", "Bold Style (<b>Bold Text</b>)", "Bullet (<li> First point...)", "Center (<center>Centered text</center>)", "Comment (<!--Comments here-->)", "Customized Body (<body...>Bgd color set</body>)", "Emphatic Style (<em>Emphasis here!</em>)", "Heading 1 (<h1>Largest</h1>)", "Heading 2 (<h2>Larger</h2>)", "Heading 3 (<h3>Large</h3>)", "Heading 4 (<h4>Small</h4>)", "Heading 5 (<h5>Smaller</h5>)", "Heading 6 (<h6>Smallest</h6>)", "Image (<img.../>)", "Italic Style (<i>Italicized Text</i>)", "New Line Marker (<br>This is the next line)", "Paragraph (<p...>I'm anchored somewhere!</p>)", "Small Style (<small>Can you even read this?</small>)", "Strikethrough Style (<s>Depreciated</s>)", "Strong Style (<strong>IMPORTANT:</strong>)", "Style Set - Line (<font...></font>)", "Style Set - Block (<span...></span>)", "Style Set - Remainder (<div...>)", "Table  (<table...>...</table)", "Teletype Style (<tt>Good for code snippet's</tt>)", "Underline Style (<u>Book Title</u>)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        v_insertHelperList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        v_insertHelperList.setName("v_insertHelperList"); // NOI18N
        v_insertHelperList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_insertHelperListMouseClicked(evt);
            }
        });
        v_insertHelperListScrollPane.setViewportView(v_insertHelperList);

        v_alignmentHelper2.setName("v_alignmentHelper2"); // NOI18N
        v_alignmentHelper2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        v_alignmentHelper2.add(jLabel2, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        v_preview.setText(resourceMap.getString("v_preview.text")); // NOI18N
        v_preview.setName("v_preview"); // NOI18N
        v_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_previewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 5;
        jPanel1.add(v_preview, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(v_alignmentHelper1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_alignmentHelper2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(v_mapNotesScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v_insertHelperListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(v_alignmentHelper2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_alignmentHelper1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v_insertHelperListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(v_mapNotesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_insertHelperListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v_insertHelperListMouseClicked
    {//GEN-HEADEREND:event_v_insertHelperListMouseClicked
        long currentTime = System.currentTimeMillis();
        if (currentTime - m_lastClickTime < 250) //Double-clicked
        {
            String snippetName = v_insertHelperList.getSelectedValue().toString();
            //If you want more complex html for a snippet example, enter if statement for it here
            if (snippetName.startsWith("Customized Body"))
                v_mapNotes.insert("<body bgcolor=\"DADADA\" align=\"center\">", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Image"))
                v_mapNotes.insert("<img src=\"http://www.path.com/to/mapimage.jpg\"/>", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Paragraph"))
                v_mapNotes.insert("<p align=\"right\">Look at me, I'm anchored over on the right side!</p>", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Style Set - Line"))
                v_mapNotes.insert("<font face=\"Times New Roman\" size=\"+3\" color=\"#ff0000\">Aren't I unique?</font>", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Style Set - Block"))
                v_mapNotes.insert("<span style=\"font-size:250%;color:660000;\">I'm huge! And I'm a special color!</span>", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Style Set - Remainder"))
                v_mapNotes.insert("<div style=\"text-align: center;\"> Sets style of text after it, but can be overcome later in html by other style-sets. (Including other div's)", v_mapNotes.getCaretPosition());
            else if (snippetName.startsWith("Table"))
                v_mapNotes.insert("<table border=\"1\"bgcolor=\"ABABAB\">\r\n"
                    + "<tr>\r\n"
                    + "<th style=\"font-size:110%;000000\"bgcolor=\"FEECE2\"colspan=\"2\">Alliances</th>\r\n"
                    + "</tr>\r\n"
                    + "<tr>\r\n"
                    + "<th bgcolor=\"ABABAB\">Axis</th>\r\n"
                    + "<th bgcolor=\"BDBDBD\">Allies</th>\r\n"
                    + "</tr>\r\n"
                    + "<tr>\r\n"
                    + "<td bgcolor=\"ABABAB\">Germany</td>\r\n"
                    + "<td bgcolor=\"BDBDBD\">Russia</td>\r\n"
                    + "</tr>\r\n"
                    + "<tr>\r\n"
                    + "<td bgcolor=\"ABABAB\">Italy</td>\r\n"
                    + "<td bgcolor=\"BDBDBD\">France</td>\r\n"
                    + "</tr>\r\n"
                    + "</table>", v_mapNotes.getCaretPosition());
            else
            {
                //The rest are grabbed from the snippet list
                String snippetHTMLStarter = snippetName.substring(snippetName.indexOf("(") + 1, snippetName.length() - 1);
                v_mapNotes.insert(snippetHTMLStarter, v_mapNotes.getCaretPosition());
            }
        }
        else
            m_lastClickTime = currentTime;
    }//GEN-LAST:event_v_insertHelperListMouseClicked

    private void v_previewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_previewActionPerformed
    {//GEN-HEADEREND:event_v_previewActionPerformed
        SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                JEditorPane editorPane = new JEditorPane();
                editorPane.setEditable(false);
                editorPane.setContentType("text/html");
                editorPane.setText(v_mapNotes.getText());

                final JScrollPane scroll = new JScrollPane(editorPane);
                final JDialog dialog = new JDialog(m_walkthroughWindow);
                dialog.setIconImage(ProgramLauncher.getProgramIcon(dialog));
                dialog.setTitle("Map Notes Preview");
                dialog.setModalityType(ModalityType.APPLICATION_MODAL);
                dialog.add(scroll, BorderLayout.CENTER);
                JPanel buttons = new JPanel();

                final JButton button = new JButton(new AbstractAction("OK")
                {
                    public void actionPerformed(ActionEvent e)
                    {
                        dialog.setVisible(false);
                    }
                });
                buttons.add(button);
                dialog.getRootPane().setDefaultButton(button);
                dialog.add(buttons, BorderLayout.SOUTH);
                dialog.pack();

                if (dialog.getWidth() < 500)
                {
                    dialog.setSize(500, dialog.getHeight());
                }
                if (dialog.getHeight() < 500)
                {
                    dialog.setSize(dialog.getWidth(), 500);
                }

                if (dialog.getWidth() > 750)
                {
                    dialog.setSize(750, dialog.getHeight());
                }
                if (dialog.getHeight() > 750)
                {
                    dialog.setSize(dialog.getWidth(), 750);
                }

                dialog.setLocationRelativeTo(m_walkthroughWindow);

                dialog.addWindowListener(new WindowAdapter()
                {
                    @Override
                    public void windowOpened(WindowEvent e)
                    {
                        scroll.getVerticalScrollBar().getModel().setValue(0);
                        scroll.getHorizontalScrollBar().getModel().setValue(0);
                        button.requestFocus();
                    }
                });

                dialog.setVisible(true);
                dialog.dispose();
            }
        });
    }//GEN-LAST:event_v_previewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel v_alignmentHelper1;
    private javax.swing.JPanel v_alignmentHelper2;
    private javax.swing.JList v_insertHelperList;
    private javax.swing.JScrollPane v_insertHelperListScrollPane;
    private javax.swing.JTextArea v_mapNotes;
    private javax.swing.JScrollPane v_mapNotesScrollPane;
    private javax.swing.JButton v_preview;
    // End of variables declaration//GEN-END:variables
}
