/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseStepContentPanel.java
 *
 * Created on May 14, 2010, 5:31:50 PM
 */

package MainProgram.Walkthrough.UI.StepContentPanels;

import Global.CommandHelper;
import Global.FileFinder;
import Global.FolderFinder;
import Global.Version;
import MainProgram.Map.MapDataExporter;
import MainProgram.UI.FileOpen;
import Utils.FileSystem;
import java.io.File;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Stephen
 */
public class Segment4Step1ContentPanel_All extends BaseStepContentPanel
{
    public Segment4Step1ContentPanel_All()
    {
        initComponents();
    }
    
    @Override
    public boolean WaitForPanelClose()
    {
        //Before we leave, attempt to delete temp map test folder
        try
        {
            if (GetMapExportFolder().exists())
                FileSystem.deleteDirectoryAndContents(GetMapExportFolder());
        }
        catch(Exception ex)
        {
        }
        
        return true;
    }
    
    @Override
    public void InitControls()
    {
        DefaultListModel model = new DefaultListModel();
        
        File tripleAParentRootFolder = FolderFinder.getTripleAParentRootFolder();
        if(!tripleAParentRootFolder.exists())
            return; //Yikes
        
        File latestTripleAFolder = null;
        Version latestVersionFound = new Version(0, 0, 0, 0);
        
        for(File tripleaVersionRoot : tripleAParentRootFolder.listFiles())
        {
            if(tripleaVersionRoot.isDirectory())
            {
                try
                {
                    String folderName = tripleaVersionRoot.getName().trim().toLowerCase();
                    String versionSection = folderName.substring(folderName.indexOf("a") + 2);
                    Version version = new Version(versionSection.replace("_", "."));
                    
                    if(version.compareTo(latestVersionFound) > 0)
                    {
                        latestTripleAFolder = tripleaVersionRoot;
                        latestVersionFound = version;
                    }
                    
                    model.addElement(folderName);
                }
                catch(Exception ex)
                {
                }
            }
        }
        
        v_installedTripleAList.setModel(model);
        if(latestTripleAFolder != null)
            v_installedTripleAList.setSelectedValue(latestTripleAFolder.getName(), true);
    }

    @Override
    public void ProcessControlContentToMapData()
    {
        //Before we leave, attempt to delete temp map test folder
        try
        {
            if (GetMapExportFolder().exists())
                FileSystem.deleteDirectoryAndContents(GetMapExportFolder());
        }
        catch(Exception ex)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        v_exportAndLaunch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        v_installedTripleAList = new javax.swing.JList();

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment4Step1ContentPanel_All.class);
        v_exportAndLaunch.setText(resourceMap.getString("v_exportAndLaunch.text")); // NOI18N
        v_exportAndLaunch.setName("v_exportAndLaunch"); // NOI18N
        v_exportAndLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_exportAndLaunchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 25;
        jPanel1.add(v_exportAndLaunch, gridBagConstraints);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        v_installedTripleAList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        v_installedTripleAList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        v_installedTripleAList.setName("v_installedTripleAList"); // NOI18N
        jScrollPane1.setViewportView(v_installedTripleAList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_exportAndLaunchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_exportAndLaunchActionPerformed
    {//GEN-HEADEREND:event_v_exportAndLaunchActionPerformed
        File tripleaJarOrExeFile = null;
        if(v_installedTripleAList.getModel().getSize() == 0) //If TripleA is not installed where we think it is
        {
            tripleaJarOrExeFile = FileFinder.FindTripleAJarOrExeFile(m_walkthroughWindow, null);
        }
        else
        {
            if(v_installedTripleAList.getSelectedValue() == null)
            {
                JOptionPane.showMessageDialog(m_walkthroughWindow, "Please select the version of TripleA you want to test your map in.");
                return;
            }
            
            File selectedTripleAFolder = new File(FolderFinder.getTripleAParentRootFolder(), v_installedTripleAList.getSelectedValue().toString());
            
            tripleaJarOrExeFile = FileFinder.FindTripleAJarOrExeFile(m_walkthroughWindow, selectedTripleAFolder);
        }
        
        //Clean out folder before proceeding
        try
        {
            if (GetMapExportFolder().exists())
                FileSystem.deleteDirectoryAndContents(GetMapExportFolder());
        }
        catch(Exception ex)
        {
        }
        MapDataExporter exporter = new MapDataExporter();
        exporter.ExportMapToFolder(GetMapData(), GetMapExportFolder(), true, m_walkthroughWindow);
        
        Process tripleaProcess = CommandHelper.executeCommandAndGetResultingProcess("java -jar \"" + tripleaJarOrExeFile.getPath() + "\" \"" + GetMapExportGameFile().getPath() + "\"");
        //try{tripleaProcess.waitFor();}catch (InterruptedException ex){}
    }//GEN-LAST:event_v_exportAndLaunchActionPerformed

    private File GetMapExportFolder()
    {
        return new File(FolderFinder.getTripleAMapsFolder(), GetMapData().GetMapName());
    }
    
    private File GetMapExportGameFile()
    {
        return new File(new File(GetMapExportFolder(), "games"), GetMapData().GetMapName() + ".xml");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton v_exportAndLaunch;
    private javax.swing.JList v_installedTripleAList;
    // End of variables declaration//GEN-END:variables
}
