/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseStepContentPanel.java
 *
 * Created on May 14, 2010, 5:31:50 PM
 */

package MainProgram.Walkthrough.UI.StepContentPanels;

import Global.CommandHelper;
import Global.FileFinder;
import Global.FolderFinder;
import MainProgram.Map.MapDataExporter;
import Utils.FileSystem;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen
 */
public class Segment5Step1ContentPanel_All extends BaseStepContentPanel
{
    public Segment5Step1ContentPanel_All()
    {
        initComponents();
    }
    
    @Override
    public boolean WaitForPanelClose()
    {
        return true;
    }
    
    @Override
    public void InitControls()
    {
    }

    @Override
    public void ProcessControlContentToMapData()
    {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        v_exportToTripleAMapFolder = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment5Step1ContentPanel_All.class);
        v_exportToTripleAMapFolder.setText(resourceMap.getString("v_exportToTripleAMapFolder.text")); // NOI18N
        v_exportToTripleAMapFolder.setName("v_exportToTripleAMapFolder"); // NOI18N
        v_exportToTripleAMapFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_exportToTripleAMapFolderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 25;
        jPanel1.add(v_exportToTripleAMapFolder, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_exportToTripleAMapFolderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_exportToTripleAMapFolderActionPerformed
    {//GEN-HEADEREND:event_v_exportToTripleAMapFolderActionPerformed
        //Clean out folder before proceeding
        try
        {
            if (GetMapExportFolder().exists())
                FileSystem.deleteDirectoryAndContents(GetMapExportFolder());
        }
        catch(Exception ex)
        {
        }
        MapDataExporter exporter = new MapDataExporter();
        exporter.ExportMapToFolder(GetMapData(), GetMapExportFolder(), true, m_walkthroughWindow);
        JOptionPane.showMessageDialog(this, "Map exported to folder!", "Map Exported", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_v_exportToTripleAMapFolderActionPerformed

    private File GetMapExportFolder()
    {
        return new File(FolderFinder.getTripleAMapsFolder(), GetMapData().GetMapName());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton v_exportToTripleAMapFolder;
    // End of variables declaration//GEN-END:variables
}
