/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageResizeWindow.java
 *
 * Created on Jun 2, 2010, 7:28:12 PM
 */

package MainProgram.Walkthrough.UI;

import MainProgram.ProgramLaunchers.ProgramLauncher;
import MainProgram.Walkthrough.UI.StepContentPanels.BaseStepContentPanel;
import java.awt.Dimension;
import org.jdesktop.application.Action;

/**
 *
 * @author Stephen
 */
public class ImageResizeWindow extends javax.swing.JDialog
{
    /** Creates new form ImageResizeWindow */
    public ImageResizeWindow(WalkthroughWindow window)
    {
        initComponents();
        setModalityType(ModalityType.APPLICATION_MODAL);
        setIconImage(ProgramLauncher.getProgramIcon(this));
        m_walkthroughWindow = window;
    }
    WalkthroughWindow m_walkthroughWindow = null;
    BaseStepContentPanel m_panel = null;
    public void InitControls(Dimension oldSize, BaseStepContentPanel panel)
    {
        m_panel = panel;
        v_widthBox.setText(Integer.toString(oldSize.width));
        v_heightBox.setText(Integer.toString(oldSize.height));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        v_cancelButton = new javax.swing.JButton();
        v_widthBox = new javax.swing.JTextField();
        v_heightBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ImageResizeWindow.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 13, -1, -1));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 63, -1, -1));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 63, -1, -1));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ImageResizeWindow.class, this);
        v_cancelButton.setAction(actionMap.get("Cancel")); // NOI18N
        v_cancelButton.setText(resourceMap.getString("v_cancelButton.text")); // NOI18N
        v_cancelButton.setName("v_cancelButton"); // NOI18N
        jPanel1.add(v_cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 92, 30));

        v_widthBox.setText(resourceMap.getString("v_widthBox.text")); // NOI18N
        v_widthBox.setName("v_widthBox"); // NOI18N
        jPanel1.add(v_widthBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, -1));

        v_heightBox.setText(resourceMap.getString("v_heightBox.text")); // NOI18N
        v_heightBox.setName("v_heightBox"); // NOI18N
        jPanel1.add(v_heightBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 90, -1));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 63, -1, -1));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 63, -1, -1));

        jButton2.setAction(actionMap.get("Close")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 92, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-433)/2, (screenSize.height-146)/2, 433, 146);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Close()
    {
        m_panel.SendGMessage(new Dimension(Integer.parseInt(v_widthBox.getText().trim()), Integer.parseInt(v_heightBox.getText().trim())));
        this.dispose();
    }

    @Action
    public void Cancel()
    {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton v_cancelButton;
    private javax.swing.JTextField v_heightBox;
    private javax.swing.JTextField v_widthBox;
    // End of variables declaration//GEN-END:variables

}
