/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WalkthroughOptionsWindow_MapInProgress.java
 *
 * Created on Jun 26, 2010, 2:13:55 AM
 */

package MainProgram.Walkthrough.UI;

import Global.ProgramSettings;
import MainProgram.ProgramLaunchers.ProgramLauncher;
import MainProgram.Walkthrough.WalkthroughData.WalkthroughOptions;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Stephen
 */
public class WalkthroughOptionsWindow_MapInProgress extends javax.swing.JDialog
{
    /** Creates new form WalkthroughOptionsWindow_MapInProgress */
    public WalkthroughOptionsWindow_MapInProgress(WalkthroughWindow window)
    {
        initComponents();
        setModalityType(ModalityType.APPLICATION_MODAL);
        setIconImage(ProgramLauncher.getProgramIcon(this));
        m_walkthroughWindow = window;

        UpdateControls(window.GetProject().GetMapData().GetWalkthroughData().GetWalkthroughOptions());
    }
    WalkthroughWindow m_walkthroughWindow = null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        v_updateOptionsButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        v_controlLevelOption1 = new javax.swing.JRadioButton();
        v_controlLevelOption2 = new javax.swing.JRadioButton();
        v_controlLevelOption3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        v_cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(WalkthroughOptionsWindow_MapInProgress.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(WalkthroughOptionsWindow_MapInProgress.class, this);
        v_updateOptionsButton.setAction(actionMap.get("UpdateOptions")); // NOI18N
        v_updateOptionsButton.setText(resourceMap.getString("v_updateOptionsButton.text")); // NOI18N
        v_updateOptionsButton.setName("v_updateOptionsButton"); // NOI18N

        jPanel7.setName("jPanel7"); // NOI18N

        buttonGroup1.add(v_controlLevelOption1);
        v_controlLevelOption1.setText(resourceMap.getString("v_controlLevelOption1.text")); // NOI18N
        v_controlLevelOption1.setName("v_controlLevelOption1"); // NOI18N

        buttonGroup1.add(v_controlLevelOption2);
        v_controlLevelOption2.setSelected(true);
        v_controlLevelOption2.setText(resourceMap.getString("v_controlLevelOption2.text")); // NOI18N
        v_controlLevelOption2.setName("v_controlLevelOption2"); // NOI18N

        buttonGroup1.add(v_controlLevelOption3);
        v_controlLevelOption3.setText(resourceMap.getString("v_controlLevelOption3.text")); // NOI18N
        v_controlLevelOption3.setName("v_controlLevelOption3"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(v_controlLevelOption1)
                .addGap(18, 18, 18)
                .addComponent(v_controlLevelOption2)
                .addGap(18, 18, 18)
                .addComponent(v_controlLevelOption3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(v_controlLevelOption1)
                    .addComponent(v_controlLevelOption2)
                    .addComponent(v_controlLevelOption3))
                .addGap(48, 48, 48))
        );

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setOpaque(true);

        v_cancelButton.setAction(actionMap.get("Cancel")); // NOI18N
        v_cancelButton.setText(resourceMap.getString("v_cancelButton.text")); // NOI18N
        v_cancelButton.setName("v_cancelButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(v_updateOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_updateOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-677)/2, (screenSize.height-191)/2, 677, 191);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void Cancel()
    {
        this.dispose();
    }
    private void UpdateControls(WalkthroughOptions options)
    {
        v_controlLevelOption1.setSelected(options.p_controlLevelOption == 0);
        v_controlLevelOption2.setSelected(options.p_controlLevelOption == 1);
        v_controlLevelOption3.setSelected(options.p_controlLevelOption == 2);
    }

    @Action
    public void UpdateOptions()
    {
        if(ProgramSettings.LoadSettings().ShowConfirmationBoxesForDataEditing && JOptionPane.showConfirmDialog(this, "Updating the walkthrough options may result in a loss of minor data. (Though unlikely)\r\n\r\nAre you sure you want to proceed?", "Proceed",JOptionPane.YES_NO_CANCEL_OPTION) != JOptionPane.YES_OPTION)
            return;
        if(CreateWalkthroughOptions().equals(m_walkthroughWindow.GetProject().GetMapData().GetWalkthroughData().GetWalkthroughOptions()))
            this.dispose();
        m_walkthroughWindow.GetProject().GetMapData().GetWalkthroughData().SetWalkthroughOptions(CreateWalkthroughOptions());
        m_walkthroughWindow.SendGMessage("WOptionsUpdate");
        this.dispose();
    }
    private WalkthroughOptions CreateWalkthroughOptions()
    {
        WalkthroughOptions options = new WalkthroughOptions();

        if(v_controlLevelOption1.isSelected())
            options.p_controlLevelOption = 0;
        else if(v_controlLevelOption2.isSelected())
            options.p_controlLevelOption = 1;
        else if(v_controlLevelOption3.isSelected())
            options.p_controlLevelOption = 2;

        return options;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton v_cancelButton;
    private javax.swing.JRadioButton v_controlLevelOption1;
    private javax.swing.JRadioButton v_controlLevelOption2;
    private javax.swing.JRadioButton v_controlLevelOption3;
    private javax.swing.JButton v_updateOptionsButton;
    // End of variables declaration//GEN-END:variables

}
