/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on May 11, 2010, 2:11:37 AM
 */

package MainProgram.UI;

import MainProgram.ProgramLaunchers.ProgramLauncher;
import org.jdesktop.application.Action;

/**
 *
 * @author Stephen
 */
public class MainMenu extends javax.swing.JFrame
{
    /** Creates new form MainMenu */
    public MainMenu()
    {
        initComponents();
        
        setIconImage(ProgramLauncher.getProgramIcon(this));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        v_importMap = new javax.swing.JButton();
        v_openRecentButton = new javax.swing.JButton();
        v_exampleImagePanel = new javax.swing.JPanel();
        v_importMapBase = new javax.swing.JButton();
        v_createMapFromScratch = new javax.swing.JButton();
        v_exitButtonHolder = new javax.swing.JPanel();
        v_exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MainMenu.class);
        setTitle(resourceMap.getString("v_mainMenu.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(250, 250));
        setName("v_mainMenu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        v_importMap.setText(resourceMap.getString("v_importMap.text")); // NOI18N
        v_importMap.setName("v_importMap"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        getContentPane().add(v_importMap, gridBagConstraints);
        v_importMap.getAccessibleContext().setAccessibleName(resourceMap.getString("v_editModButton.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(MainMenu.class, this);
        v_openRecentButton.setAction(actionMap.get("ShowRecentProjectForOpen")); // NOI18N
        v_openRecentButton.setText(resourceMap.getString("v_openRecentButton.text")); // NOI18N
        v_openRecentButton.setToolTipText(resourceMap.getString("v_openRecentButton.toolTipText")); // NOI18N
        v_openRecentButton.setName("v_openRecentButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        getContentPane().add(v_openRecentButton, gridBagConstraints);

        v_exampleImagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        v_exampleImagePanel.setName("v_exampleImagePanel"); // NOI18N
        v_exampleImagePanel.setOpaque(false);
        v_exampleImagePanel.setPreferredSize(new java.awt.Dimension(463, 398));

        javax.swing.GroupLayout v_exampleImagePanelLayout = new javax.swing.GroupLayout(v_exampleImagePanel);
        v_exampleImagePanel.setLayout(v_exampleImagePanelLayout);
        v_exampleImagePanelLayout.setHorizontalGroup(
            v_exampleImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        v_exampleImagePanelLayout.setVerticalGroup(
            v_exampleImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 99.0;
        gridBagConstraints.weighty = 99.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 0, 25);
        getContentPane().add(v_exampleImagePanel, gridBagConstraints);

        v_importMapBase.setText(resourceMap.getString("v_importMapBase.text")); // NOI18N
        v_importMapBase.setName("v_importMapBase"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        getContentPane().add(v_importMapBase, gridBagConstraints);

        v_createMapFromScratch.setAction(actionMap.get("startMapFromScratchWalkthrough")); // NOI18N
        v_createMapFromScratch.setText(resourceMap.getString("v_createMapFromScratch.text")); // NOI18N
        v_createMapFromScratch.setToolTipText(resourceMap.getString("v_createMapFromScratch.toolTipText")); // NOI18N
        v_createMapFromScratch.setName("v_createMapFromScratch"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 0, 0);
        getContentPane().add(v_createMapFromScratch, gridBagConstraints);

        v_exitButtonHolder.setName("v_exitButtonHolder"); // NOI18N
        v_exitButtonHolder.setLayout(new java.awt.GridBagLayout());

        v_exitButton.setAction(actionMap.get("quit")); // NOI18N
        v_exitButton.setMnemonic('\uffff');
        v_exitButton.setText(resourceMap.getString("v_exitButton.text")); // NOI18N
        v_exitButton.setToolTipText(resourceMap.getString("v_exitButton.toolTipText")); // NOI18N
        v_exitButton.setName("v_exitButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.ipady = 12;
        v_exitButtonHolder.add(v_exitButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 15, 25);
        getContentPane().add(v_exitButtonHolder, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-829)/2, (screenSize.height-425)/2, 829, 425);
    }// </editor-fold>//GEN-END:initComponents
    boolean m_reset = false;

    @Action
    public void startMapFromScratchWalkthrough()
    {
        WalkthroughOptionsWindow_MapFromScratch walkthroughOptionsWindow = new WalkthroughOptionsWindow_MapFromScratch(this);
        walkthroughOptionsWindow.setLocationRelativeTo(this);
        walkthroughOptionsWindow.setVisible(true);

        this.setVisible(false);
    }

    @Action
    public void ShowRecentProjectForOpen()
    {
        RecentProjectsWindow window = new RecentProjectsWindow(this);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
        
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton v_createMapFromScratch;
    private javax.swing.JPanel v_exampleImagePanel;
    private javax.swing.JButton v_exitButton;
    private javax.swing.JPanel v_exitButtonHolder;
    private javax.swing.JButton v_importMap;
    private javax.swing.JButton v_importMapBase;
    private javax.swing.JButton v_openRecentButton;
    // End of variables declaration//GEN-END:variables

}
