/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WalkthroughOptionsWindow_MapFromScratch.java
 *
 * Created on May 11, 2010, 5:18:06 PM
 */

package MainProgram.UI;

import Global.Enums;
import MainProgram.Map.MapData;
import MainProgram.ProgramLaunchers.ProgramLauncher;
import MainProgram.Project.Project;
import MainProgram.Project.ProjectInformation;
import org.jdesktop.application.Action;
import MainProgram.Walkthrough.WalkthroughData.WalkthroughOptions;
import MainProgram.Walkthrough.UI.WalkthroughWindow;
import MainProgram.Walkthrough.WalkthroughData.WalkthroughData;
import MainProgram.Walkthrough.WalkthroughStep;

/**
 *
 * @author Stephen
 */
public class WalkthroughOptionsWindow_MapFromScratch extends javax.swing.JFrame {

    private MainMenu m_mainMenu = null;
    /** Creates new form WalkthroughOptionsWindow_MapFromScratch */
    public WalkthroughOptionsWindow_MapFromScratch(MainMenu main)
    {
        initComponents();
        setIconImage(ProgramLauncher.getProgramIcon(this));
        m_mainMenu = main;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        v_beginWalkthroughButton = new javax.swing.JButton();
        v_backButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        v_controlLevelOption1 = new javax.swing.JRadioButton();
        v_controlLevelOption2 = new javax.swing.JRadioButton();
        v_controlLevelOption3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(WalkthroughOptionsWindow_MapFromScratch.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                WalkthroughOptionsWindow_MapFromScratch.this.windowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(WalkthroughOptionsWindow_MapFromScratch.class, this);
        v_beginWalkthroughButton.setAction(actionMap.get("BeginWalkthrough")); // NOI18N
        v_beginWalkthroughButton.setText(resourceMap.getString("v_beginWalkthroughButton.text")); // NOI18N
        v_beginWalkthroughButton.setName("v_beginWalkthroughButton"); // NOI18N
        getContentPane().add(v_beginWalkthroughButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 133, 33));

        v_backButton.setAction(actionMap.get("GoBack")); // NOI18N
        v_backButton.setFont(resourceMap.getFont("v_backButton.font")); // NOI18N
        v_backButton.setText(resourceMap.getString("v_backButton.text")); // NOI18N
        v_backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        v_backButton.setName("v_backButton"); // NOI18N
        getContentPane().add(v_backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPanel7.setName("jPanel7"); // NOI18N

        buttonGroup1.add(v_controlLevelOption1);
        v_controlLevelOption1.setText(resourceMap.getString("v_controlLevelOption1.text")); // NOI18N
        v_controlLevelOption1.setName("v_controlLevelOption1"); // NOI18N

        buttonGroup1.add(v_controlLevelOption2);
        v_controlLevelOption2.setSelected(true);
        v_controlLevelOption2.setText(resourceMap.getString("v_controlLevelOption2.text")); // NOI18N
        v_controlLevelOption2.setName("v_controlLevelOption2"); // NOI18N

        buttonGroup1.add(v_controlLevelOption3);
        v_controlLevelOption3.setText(resourceMap.getString("v_controlLevelOption3.text")); // NOI18N
        v_controlLevelOption3.setName("v_controlLevelOption3"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(v_controlLevelOption1)
                .addGap(18, 18, 18)
                .addComponent(v_controlLevelOption2)
                .addGap(18, 18, 18)
                .addComponent(v_controlLevelOption3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(v_controlLevelOption1)
                    .addComponent(v_controlLevelOption2)
                    .addComponent(v_controlLevelOption3))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 40));

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 510, 28));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-677)/2, (screenSize.height-191)/2, 677, 191);
    }// </editor-fold>//GEN-END:initComponents

    private void windowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_windowClosing
    {//GEN-HEADEREND:event_windowClosing
        GoBack();
    }//GEN-LAST:event_windowClosing

    @Action
    public void GoBack()
    {
        m_mainMenu.setVisible(true);
        this.dispose();
    }

    @Action
    public void BeginWalkthrough()
    {
        WalkthroughWindow window = new WalkthroughWindow(m_mainMenu, Enums.LaunchType.MapFromScratch, CreateProject());
        window.setVisible(true);

        this.setVisible(false);
    }
    private WalkthroughOptions CreateWalkthroughOptions()
    {
        WalkthroughOptions options = new WalkthroughOptions();

        if(v_controlLevelOption1.isSelected())
            options.p_controlLevelOption = 0;
        else if(v_controlLevelOption2.isSelected())
            options.p_controlLevelOption = 1;
        else if(v_controlLevelOption3.isSelected())
            options.p_controlLevelOption = 2;

        return options;
    }
    private MapData CreateMapData()
    {
        MapData result = new MapData(CreateWalkthroughData());
        return result;
    }
    private Project CreateProject()
    {
        Project result = new Project(CreateMapData(), CreateProjectInformation());
        return result;
    }
    private ProjectInformation CreateProjectInformation()
    {
        ProjectInformation result = new ProjectInformation();
        return result;
    }
    private WalkthroughData CreateWalkthroughData()
    {
        WalkthroughData result = new WalkthroughData(CreateWalkthroughOptions(), new WalkthroughStep(0, 0));
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton v_backButton;
    private javax.swing.JButton v_beginWalkthroughButton;
    private javax.swing.JRadioButton v_controlLevelOption1;
    private javax.swing.JRadioButton v_controlLevelOption2;
    private javax.swing.JRadioButton v_controlLevelOption3;
    // End of variables declaration//GEN-END:variables
}
