/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Segment1StepListPanel.java
 *
 * Created on May 19, 2010, 4:51:42 PM
 */

package MainProgram.Walkthrough.UI.SegmentStepListPanels;

import MainProgram.Walkthrough.UI.WalkthroughWindow;

/**
 *
 * @author Stephen
 */
public class BaseSegmentListPanel extends javax.swing.JPanel
{
    WalkthroughWindow m_walkthroughWindow = null;

    /** Creates new form Segment2StepListPanel */
    public BaseSegmentListPanel(WalkthroughWindow window)
    {
        initComponents();

        m_walkthroughWindow = window;
    }

    public void UpdateControls()
    {
        //Code specified in child classes
    }
    public void FocusOnFirstButton()
    {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(190, 300));
        setMinimumSize(new java.awt.Dimension(190, 300));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(190, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
