/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Segment1StepListPanel.java
 *
 * Created on May 19, 2010, 4:51:42 PM
 */

package MainProgram.Walkthrough.UI.SegmentStepListPanels;

import Global.Constants;
import MainProgram.Walkthrough.UI.WalkthroughWindow;
import MainProgram.Walkthrough.WalkthroughStep;
import java.awt.Color;
import org.jdesktop.application.Action;

/**
 *
 * @author Stephen
 */
public class Segment3StepListPanel extends BaseSegmentListPanel
{
    /** Creates new form Segment3StepListPanel */
    public Segment3StepListPanel(WalkthroughWindow window)
    {
        super(window);

        initComponents();
    }
    
    @Override
    public void UpdateControls()
    {
        WalkthroughStep step = m_walkthroughWindow.GetCurrentStep();
        WalkthroughStep fstep = m_walkthroughWindow.GetFarthestStep();
        v_step1Button.setEnabled(fstep.GetSegment() > 2 || fstep.GetStep() >= -1);
        v_step2Button.setEnabled(fstep.GetSegment() > 2 || fstep.GetStep() >= 0);
        v_step3Button.setEnabled(fstep.GetSegment() > 2 || fstep.GetStep() >= 1);
        v_step4Button.setEnabled(fstep.GetSegment() > 2 || fstep.GetStep() >= 2);

        v_step1Button.setBackground(GetConstantColorFromStepIndex(0, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step2Button.setBackground(GetConstantColorFromStepIndex(1, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step3Button.setBackground(GetConstantColorFromStepIndex(2, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step4Button.setBackground(GetConstantColorFromStepIndex(3, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
    }
    
    @Override
    public void FocusOnFirstButton()
    {
        v_step1Button.requestFocusInWindow();
    }
    
    private Color GetConstantColorFromStepIndex(int buttonIndex, int fsegment, int step, int stepIndex)
    {
        if(fsegment > 2)
        {
            if(step == buttonIndex)
                return Constants.HighlightedSegmentBackColor;
            else
                return Constants.FinishedSegmentBackColor;
        }
        else
        {
            if(step == buttonIndex)
                return Constants.HighlightedSegmentBackColor;
            else if(stepIndex <= buttonIndex)
                return Constants.DefaultButtonBackColor;
            else
                return Constants.FinishedSegmentBackColor;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_step1Button = new javax.swing.JButton();
        v_step2Button = new javax.swing.JButton();
        v_step3Button = new javax.swing.JButton();
        v_step4Button = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(190, 300));
        setMinimumSize(new java.awt.Dimension(190, 300));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(190, 300));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(Segment3StepListPanel.class, this);
        v_step1Button.setAction(actionMap.get("ShowStep1")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment3StepListPanel.class);
        v_step1Button.setText(resourceMap.getString("v_step1Button.text")); // NOI18N
        v_step1Button.setName("v_step1Button"); // NOI18N

        v_step2Button.setAction(actionMap.get("ShowStep2")); // NOI18N
        v_step2Button.setText(resourceMap.getString("v_step2Button.text")); // NOI18N
        v_step2Button.setName("v_step2Button"); // NOI18N

        v_step3Button.setAction(actionMap.get("ShowStep3")); // NOI18N
        v_step3Button.setText(resourceMap.getString("v_step3Button.text")); // NOI18N
        v_step3Button.setName("v_step3Button"); // NOI18N

        v_step4Button.setAction(actionMap.get("ShowStep4")); // NOI18N
        v_step4Button.setText(resourceMap.getString("v_step4Button.text")); // NOI18N
        v_step4Button.setName("v_step4Button"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v_step1Button, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(v_step2Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(v_step3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(v_step4Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(v_step1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void ShowStep1()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(2, 0));
    }

    @Action
    public void ShowStep2()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(2, 1));
    }

    @Action
    public void ShowStep3()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(2, 2));
    }

    @Action
    public void ShowStep4()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(2, 3));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton v_step1Button;
    private javax.swing.JButton v_step2Button;
    private javax.swing.JButton v_step3Button;
    private javax.swing.JButton v_step4Button;
    // End of variables declaration//GEN-END:variables
}
