/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Segment1StepListPanel.java
 *
 * Created on May 19, 2010, 4:51:42 PM
 */

package MainProgram.Walkthrough.UI.SegmentStepListPanels;

import Global.Constants;
import MainProgram.Walkthrough.UI.WalkthroughWindow;
import MainProgram.Walkthrough.WalkthroughStep;
import java.awt.Color;
import org.jdesktop.application.Action;

/**
 *
 * @author Stephen
 */
public class Segment2StepListPanel extends BaseSegmentListPanel
{
    /** Creates new form Segment2StepListPanel */
    public Segment2StepListPanel(WalkthroughWindow window)
    {
        super(window);

        initComponents();
    }
    @Override
    public void UpdateControls()
    {
        WalkthroughStep step = m_walkthroughWindow.GetCurrentStep();
        WalkthroughStep fstep = m_walkthroughWindow.GetFarthestStep();
        v_step1Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= -1);
        v_step2Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 0);
        v_step3Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 1);
        v_step4Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 2);
        v_step5Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 3);
        v_step6Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 4);
        v_step7Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 5);
        v_step8Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 6);
        v_step9Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 7);
        v_step10Button.setEnabled(fstep.GetSegment() > 1 || fstep.GetStep() >= 8);


        v_step1Button.setBackground(GetConstantColorFromStepIndex(0, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step2Button.setBackground(GetConstantColorFromStepIndex(1, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step3Button.setBackground(GetConstantColorFromStepIndex(2, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step4Button.setBackground(GetConstantColorFromStepIndex(3, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step5Button.setBackground(GetConstantColorFromStepIndex(4, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step6Button.setBackground(GetConstantColorFromStepIndex(5, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step7Button.setBackground(GetConstantColorFromStepIndex(6, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step8Button.setBackground(GetConstantColorFromStepIndex(7, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step9Button.setBackground(GetConstantColorFromStepIndex(8, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
        v_step10Button.setBackground(GetConstantColorFromStepIndex(9, fstep.GetSegment(), step.GetStep(), fstep.GetStep()));
    }
    @Override
    public void FocusOnFirstButton()
    {
        v_step1Button.requestFocusInWindow();
    }
    private Color GetConstantColorFromStepIndex(int buttonIndex, int fsegment, int step, int stepIndex)
    {
        if(fsegment > 1)
        {
            if(step == buttonIndex)
                return Constants.HighlightedSegmentBackColor;
            else
                return Constants.FinishedSegmentBackColor;
        }
        else
        {
            if(step == buttonIndex)
                return Constants.HighlightedSegmentBackColor;
            else if(stepIndex <= buttonIndex)
                return Constants.DefaultButtonBackColor;
            else
                return Constants.FinishedSegmentBackColor;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_step1Button = new javax.swing.JButton();
        v_step2Button = new javax.swing.JButton();
        v_step3Button = new javax.swing.JButton();
        v_step4Button = new javax.swing.JButton();
        v_step5Button = new javax.swing.JButton();
        v_step7Button = new javax.swing.JButton();
        v_step6Button = new javax.swing.JButton();
        v_step8Button = new javax.swing.JButton();
        v_step9Button = new javax.swing.JButton();
        v_step10Button = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(190, 401));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(190, 401));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(Segment2StepListPanel.class, this);
        v_step1Button.setAction(actionMap.get("ShowStep1")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Segment2StepListPanel.class);
        v_step1Button.setText(resourceMap.getString("v_step1Button.text")); // NOI18N
        v_step1Button.setName("v_step1Button"); // NOI18N

        v_step2Button.setAction(actionMap.get("ShowStep2")); // NOI18N
        v_step2Button.setText(resourceMap.getString("v_step2Button.text")); // NOI18N
        v_step2Button.setName("v_step2Button"); // NOI18N

        v_step3Button.setAction(actionMap.get("ShowStep3")); // NOI18N
        v_step3Button.setText(resourceMap.getString("v_step3Button.text")); // NOI18N
        v_step3Button.setName("v_step3Button"); // NOI18N

        v_step4Button.setAction(actionMap.get("ShowStep4")); // NOI18N
        v_step4Button.setText(resourceMap.getString("v_step4Button.text")); // NOI18N
        v_step4Button.setName("v_step4Button"); // NOI18N

        v_step5Button.setAction(actionMap.get("ShowStep5")); // NOI18N
        v_step5Button.setText(resourceMap.getString("v_step5Button.text")); // NOI18N
        v_step5Button.setName("v_step5Button"); // NOI18N

        v_step7Button.setAction(actionMap.get("ShowStep7")); // NOI18N
        v_step7Button.setText(resourceMap.getString("v_step7Button.text")); // NOI18N
        v_step7Button.setName("v_step7Button"); // NOI18N

        v_step6Button.setAction(actionMap.get("ShowStep6")); // NOI18N
        v_step6Button.setText(resourceMap.getString("v_step6Button.text")); // NOI18N
        v_step6Button.setName("v_step6Button"); // NOI18N

        v_step8Button.setAction(actionMap.get("ShowStep8")); // NOI18N
        v_step8Button.setText(resourceMap.getString("v_step8Button.text")); // NOI18N
        v_step8Button.setName("v_step8Button"); // NOI18N

        v_step9Button.setAction(actionMap.get("ShowStep9")); // NOI18N
        v_step9Button.setText(resourceMap.getString("v_step9Button.text")); // NOI18N
        v_step9Button.setName("v_step9Button"); // NOI18N

        v_step10Button.setAction(actionMap.get("ShowStep10")); // NOI18N
        v_step10Button.setText(resourceMap.getString("v_step10Button.text")); // NOI18N
        v_step10Button.setName("v_step10Button"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(v_step3Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step4Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step5Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step6Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step2Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step1Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(v_step7Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step8Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(v_step9Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(v_step10Button, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(v_step1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_step10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void ShowStep1()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 0));
    }

    @Action
    public void ShowStep2()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 1));
    }

    @Action
    public void ShowStep3()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 2));
    }

    @Action
    public void ShowStep4()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 3));
    }

    @Action
    public void ShowStep5()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 4));
    }

    @Action
    public void ShowStep6()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 5));
    }

    @Action
    public void ShowStep7()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 6));
    }

    @Action
    public void ShowStep8()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 7));
    }

    @Action
    public void ShowStep9()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 8));
    }

    @Action
    public void ShowStep10()
    {
        m_walkthroughWindow.SetCurrentStep(new WalkthroughStep(1, 9));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton v_step10Button;
    private javax.swing.JButton v_step1Button;
    private javax.swing.JButton v_step2Button;
    private javax.swing.JButton v_step3Button;
    private javax.swing.JButton v_step4Button;
    private javax.swing.JButton v_step5Button;
    private javax.swing.JButton v_step6Button;
    private javax.swing.JButton v_step7Button;
    private javax.swing.JButton v_step8Button;
    private javax.swing.JButton v_step9Button;
    // End of variables declaration//GEN-END:variables

}
